version: "3.9"

services:
  # ---------------------------
  # PostgreSQL
  # ---------------------------
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: usersdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - appnet

  # ---------------------------
  # API 1 — EXPRESS (2 instâncias)
  # ---------------------------
  api1-express-1:
    build: ./api1-express
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/usersdb?schema=api1_schema"
    networks:
      - appnet

  api1-express-2:
    build: ./api1-express
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/usersdb?schema=api1_schema"
    networks:
      - appnet

  # ---------------------------
  # API 2 — FASTAPI (2 instâncias)
  # ---------------------------
  api2-fastapi-1:
    build: ./api2-fastapi
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: usersdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      SCHEMA: api2_schema
    networks:
      - appnet

  api2-fastapi-2:
    build: ./api2-fastapi
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: usersdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      SCHEMA: api2_schema
    networks:
      - appnet

  # ---------------------------
  # API 3 — NESTJS (2 instâncias)
  # ---------------------------
  api3-nestjs-1:
    build: ./api3-nestjs
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/usersdb?schema=api3_schema"
    networks:
      - appnet

  api3-nestjs-2:
    build: ./api3-nestjs
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/usersdb?schema=api3_schema"
    networks:
      - appnet

  # ---------------------------
  # GATEWAY NGINX
  # ---------------------------
  gateway:
    image: nginx:stable-alpine
    container_name: gateway
    ports:
      - "8080:80"
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1-express-1
      - api1-express-2
      - api2-fastapi-1
      - api2-fastapi-2
      - api3-nestjs-1
      - api3-nestjs-2
    networks:
      - appnet

volumes:
  pgdata:

networks:
  appnet:
    driver: bridge
